AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main Root Stack - Connects all nested CloudFormation stacks'

Parameters:
  KeyName:
    Type: String
    Default: 'new-key'
    Description: EC2 Key Pair Name
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR for VPC

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ahmed15102002.s3.amazonaws.com/templates/vpc.yaml
      Parameters:
        VpcCidr: !Ref VpcCidr

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ahmed15102002.s3.amazonaws.com/templates/security.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
    DependsOn: VPCStack

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ahmed15102002.s3.amazonaws.com/templates/database.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateSubnets: !GetAtt VPCStack.Outputs.PrivateSubnets
        RDSSecurityGroupId: !GetAtt SecurityStack.Outputs.RDSSecurityGroupId
    DependsOn: SecurityStack

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ahmed15102002.s3.amazonaws.com/templates/compute.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnets: !GetAtt VPCStack.Outputs.PublicSubnets
        PrivateSubnets: !GetAtt VPCStack.Outputs.PrivateSubnets
        KeyName: !Ref KeyName
        ALBSecurityGroupId: !GetAtt SecurityStack.Outputs.ALBSecurityGroupId
        EC2SecurityGroupId: !GetAtt SecurityStack.Outputs.EC2SecurityGroupId
        RDSInstanceEndpoint: !GetAtt DatabaseStack.Outputs.RDSInstanceEndpoint
    DependsOn: DatabaseStack

Outputs:
  VpcId:
    Description: The ID of the created VPC
    Value: !GetAtt VPCStack.Outputs.VpcId

  LoadBalancerDNS:
    Description: ALB DNS from Compute stack
    Value: !GetAtt ComputeStack.Outputs.LoadBalancerDNS

  RDSInstanceEndpoint:
    Description: Endpoint of RDS Instance
    Value: !GetAtt DatabaseStack.Outputs.RDSInstanceEndpoint
